[pytest]
base_url = https://www.saucedemo.com/
pythonpath = .


markers =
    api: API tests no browser
    ui: UI tests with browser
    

#slowmo and headed(with browser)
addopts = 
    --browser=chromium 
    --headed 
    --slowmo=1500
    #--tracing= on
    --screenshot=on
    #--video=reatain-on-failure
    --html=report.html
    --self-contained-html
    --strict-markers



importmode = importlib