[pytest]
base_url = https://www.saucedemo.com/
pythonpath = .

#slowmo and headed(with browser)
addopts = 
    --browser=chromium 
    --headed 
    --slowmo=1500
    #--tracing= on
    --screenshot=on
    #--video=reatain-on-failure
    --html=report.html
    --self-contained-html


[pytest]
importmode = importlib